#
# This is a Makefile for the gb code base package
#

#remove any existing gopath
unexport GOPATH

#Include the core Makefile and all its targets
include ../../../Makefile.core

#Include the gb Makefile include
include ../../../Makefile.gb